// Arabic UI strings (hardcoded; content/strings.json may be supplied by the
// server later, but the client never depends on it).

export const STR = {
  appName: "THE LAST PLAYER",
  appTagline: "آخر لاعب يبقى… يفوز 🏆",
  joinTitle: "ادخل الساحة",
  nameLabel: "اسم اللاعب",
  namePlaceholder: "مثال: صقر الصحراء",
  codeLabel: "رمز الغرفة (اختياري)",
  codePlaceholder: "مثال: K7Q2",
  joinBtn: "⚔️ ادخل المعركة",
  joinHint: "اترك الرمز فارغًا لإنشاء غرفة جديدة",
  connecting: "جارٍ الاتصال بالساحة…",
  serverLabel: "السيرفر",
  nameRequired: "اكتب اسمك أولًا يا بطل",
  lobbyTitle: "غرفة الانتظار",
  roomCode: "رمز الغرفة",
  copy: "نسخ",
  copied: "تم نسخ الرمز ✓",
  playersInRoom: "لاعب في الغرفة",
  waitingForPlayers: "بانتظار انضمام اللاعبين…",
  shareCode: "شارك الرمز مع أصدقائك للدخول",
  startBtn: "🚀 ابدأ المعركة",
  startHint: (min: number) => `يحتاج ${min} لاعبين على الأقل للبدء`,
  hostBadge: "المضيف",
  youBadge: "أنت",
  getReady: "استعد…",
  nextRound: "الجولة القادمة",
  round: "الجولة",
  roundEndTitle: "🏁 نهاية الجولة",
  survivors: "الناجون",
  eliminatedList: "المُقصَون",
  standings: "الترتيب",
  nextSoon: "الجولة التالية تبدأ خلال لحظات…",
  eliminatedTitle: "تم إقصاؤك 💀",
  spectatorNote: "أنت الآن متفرج — تابع المعركة حتى النهاية",
  aliveNow: "ما زالوا أحياء",
  winner: "الفائز",
  champion: "🏆 البطل — آخر لاعب صامد",
  playAgain: "🔄 غرفة جديدة",
  disconnected: "انقطع الاتصال",
  disconnectedHint: "يبدو أن الاتصال بالساحة انقطع",
  rejoin: "إعادة الانضمام",
  codeNotFound: "لم يتم العثور على الرمز — تم إنشاء غرفة جديدة",
  waitingRound: "جولة جديدة على وشك أن تبدأ…",
  answerSent: "تم إرسال إجابتك ✓",
  chooseAnswer: "اختر الإجابة الصحيحة بأسرع ما يمكن",
  hideTitle: "اختر مخبأك!",
  hideHint: "اضغط على أي مربع للاختباء — يمكنك تغيير مخبأك حتى نهاية الوقت",
  seekTitle: "🔍 أنت الباحث!",
  seekHint: "اختر ٣ مربعات تظن أن اللاعبين مختبئون فيها",
  confirmPicks: "تأكيد الاختيار",
  hidersWait: "المختبئون ينتظرون… الباحثون يتحركون الآن",
  reactWait: "انتظر الضوء الأخضر…",
  reactTap: "اضغط الآن! ⚡",
  reactHint: "٥ محاولات — الضغط المبكر يُلغي المحاولة",
  attempt: "المحاولة",
  survivalTitle: "اهرب من مناطق الخطر!",
  survivalHint: "تحرك كل جولة إلى منطقة مجاورة — البقاء في مكانك أو دخول منطقة خطرة = إقصاء",
  moved: "تم التحرك ✓",
  duelTitle: "النزال الأخير ⚔️",
  duelHint: "أجب بسرعة ودقة — الأسرع إجابة صحيحة يكسب النقطة، والأول إلى ٣ نقاط يفوز",
  duelPlaceholder: "اكتب إجابتك هنا…",
  duelSend: "إرسال الإجابة",
  duelSent: "تم إرسال إجابتك — بانتظار الخصم…",
  bout: "النزال",
  toastError: "حدث خطأ",
};

export const ROUND_TITLES: Record<string, string> = {
  quiz_race: "⚡ سباق الأسئلة",
  hide_seek: "🙈 الاختباء والبحث",
  react_race: "🟢 سباق رد الفعل",
  survival: "🔥 البقاء للأقوى",
  final_duel: "⚔️ النزال الأخير",
};

export function roundTitle(type: string, fallback?: string): string {
  return fallback || ROUND_TITLES[type] || `جولة: ${type}`;
}
